### ISSUE TITLE
Bug with start_host

### ISSUE THREAD

**Issue by saneery** [flambard/enet#11]
gen_udp opens two times, the first time here:
https://github.com/flambard/enet/blob/5a493ff7603677db4d9a380690d6e9dde271201a/src/enet.erl#L32
and a second time here:
https://github.com/flambard/enet/blob/5a493ff7603677db4d9a380690d6e9dde271201a/src/enet_host.erl#L112
as result I have two ports:
![image](https://user-images.githubusercontent.com/11743366/52902238-5270a600-321f-11e9-908c-898e464abad3.png)
and match error in `handle_info`, because Socket in State and Socket in the message disagrees:
https://github.com/flambard/enet/blob/5a493ff7603677db4d9a380690d6e9dde271201a/src/enet_host.erl#L205-L209

I think it's because of this option `reuseaddr`:
https://github.com/flambard/enet/blob/5a493ff7603677db4d9a380690d6e9dde271201a/src/enet_host.erl#L52

**Comment by flambard** [comment]
You are quite right. Thank you for the very well written bug report! A fix has been pushed.

**Comment by saneery** [comment]
thank you for fix this 🙏
