### ISSUE TITLE
Compatibility with C based (original) enet

### ISSUE THREAD

**Issue by Ablu** [flambard/enet#3]
Hi,

I wonder, is this library compatible / tested against the C based enet implementation?

To me it looks like  the `Compressed` and `SentTimeIncluded` bits are swapped compared to the official enet. But even after changing that I run into issues with the command parsing...

Regards,
Ablu

**Comment by flambard** [comment]
Hi!

The aim is that this library will be perfectly compatible with the C implementation. However, this is a work in progress with some significant parts still left to be implemented.

I'm planning to test it against the C implementation but I have not done so yet. Currently I have only tested it against itself.

You seem to have started to test it against the C implementation, correct? I will take a look at the `Compressed` and `SentTimeIncluded` bits.

Thank you for reporting this! If you'd like you are most welcome to try it out against the C implementation and report any discrepancies.

**Comment by Ablu** [comment]
Ah okay. That explains some things :).

I tried poking around in the code for a bit. After switching the order of the bits I get to:
~~~
21:11:20.393 [error] ** State machine #PID<0.185.0> terminating
** Last event = {{:timeout, {255, 8625, 1}}, [<<131, 255, 0, 1>>, <<0, 0, 0, 0, 0, 0, 5, 120, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 19, 136, 0, 0, 0, 2, 0, 0, 0, 2, 145, 93, 51, 167>>]}
** When server state  = {:verifying_connect, {:state, #PID<0.177.0>, #PID<0.180.0>, #PID<0.184.0>, %{0 => #PID<0.186.0>}, {192, 168, 0, 192}, 52120, 0, 0, 255, 255, 0, 0, 65536, 5000, 2, 2, 2, 0, 1, 0, 2438804391}}
** Reason for termination = :error::function_clause
** Callback mode = [:state_functions, :state_enter]
** Stacktrace =
**  [{:enet_peer, :handle_event, [{:timeout, {255, 8625, 1}}, [<<131, 255, 0, 1>>, <<0, 0, 0, 0, 0, 0, 5, 120, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 19, 136, 0, 0, 0, 2, 0, 0, 0, 2, 145, 93, 51, 167>>], {:state, #PID<0.177.0>, #PID<0.180.0>, #PID<0.184.0>, %{0 => #PID<0.186.0>}, {192, 168, 0, 192}, 52120, 0, 0, 255, 255, 0, 0, 65536,5000, 2, 2, 2, 0, 1, 0, 2438804391}], [file: '/home/ablu/mana/enet/src/enet_peer.erl', line: 808]}, {:gen_statem, :call_state_function, 5, [file: 'gen_statem.erl', line: 1633]}, {:gen_statem, :loop_event_state_function, 6, [file: 'gen_statem.erl', line: 1023]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]
~~~
(line numbers might be slightly off since I added some debug prints).

The C++ program I used simply opens a connection using a code like:
~~~c++
    ENetAddress enetAddress;
    enet_address_set_host(&enetAddress, address.c_str());
    enetAddress.port = port;
    mLocal = enet_host_create(nullptr /* create a client host */,
                              1 /* allow one outgoing connection */,
                              0           /* unlimited channel count */,
                              0 /* assume any amount of incoming bandwidth */,
                              0 /* assume any amount of outgoing bandwidth */);


    if (!mLocal)
        return false;

    // Initiate the connection, allocating channel 0.
    mRemote = enet_host_connect(mLocal, &enetAddress, 1, 0);

    ENetEvent event;
    if (enet_host_service(mLocal, &event, 10000) <= 0 ||
        event.type != ENET_EVENT_TYPE_CONNECT)
    {
        stop();
        return false;
    }
~~~
The C++ code runds into the `stop();` code. So in the end it looks like both parts timed out.

On wireshark I see:
~~~
client sends:
8f:ff:e1:51:82:ff:00:01:00:00:ff:ff:00:00:05:78:00:01:00:00:00:00:00:01:00:00:00:00:00:00:00:00:00:00:13:88:00:00:00:02:00:00:00:02:22:5c:b2:d9:00:00:00:00

server sends:
40:00:e1:52:01:ff:00:00:00:01:e1:51

server sends:
40:00:e1:53:83:ff:00:01:00:00:00:00:00:00:05:78:00:01:00:00:00:00:00:01:00:00:00:00:00:00:00:00:00:00:13:88:00:00:00:02:00:00:00:02:22:5c:b2:d9
~~~

After that no messages are exchanged and both parties time out.

Nice code btw. It reads 1000x easier than the original enet code :P

**Comment by flambard** [comment]
Thanks a ton for this report! I will investigate and try to figure out what is going wrong here. My time is limited so it might take a while though.

The `Compressed` and `SentTimeIncluded` bits are now swapped in master.

Thanks. I try to keep the code clean :-) Having separate processes for hosts, peers, and channels also really helps keeping things tidy.

**Comment by Ablu** [comment]
> The Compressed and SentTimeIncluded bits are now swapped in master.

Thanks for the fix. I forgot to apply it to the encoding part I think... The connection is now established successfully. It seems to fail at receiving / decoding the message now:
~~~
22:30:48.436 [error] ** State machine #PID<0.185.0> terminating** Last event = {:cast, {:incoming_packet, 63079, <<1, 255, 0, 1, 0, 1, 246, 2, 134, 0, 0, 1, 0, 31, 5, 0, 0, 0, 0, 9, 108, 111, 99, 97, 108, 104, 111, 115, 116, 37, 132, 0, 8, 99, 104, 97, 110, 103, 101, 77, 101, 0, 0, 0, 0>>}}
** When server state  = {:verifying_connect, {:state, #PID<0.177.0>, #PID<0.180.0>, #PID<0.184.0>, %{0 => #PID<0.186.0>}, {192, 168, 0, 192}, 58602, 0, 0, 255, 255, 0, 0, 65536, 5000, 2, 2, 2, 0, 1, 0, 576575497}}** Reason for termination = :error:{:badmatch, <<0, 0, 0, 9, 108, 111, 99, 97, 108, 104, 111, 115, 116, 37, 132, 0, 8, 99, 104, 97, 110, 103, 101, 77, 101, 0, 0, 0, 0>>}** Callback mode = [:state_functions, :state_enter]
** Stacktrace =
**  [{:enet_protocol_decode, :command, 2, [file: '/home/ablu/mana/enet/src/enet_protocol_decode.erl', line: 140]}, {:enet_protocol_decode, :commands, 2, [file: '/home/ablu/mana/enet/src/enet_protocol_decode.erl', line: 43]}, {:enet_protocol_decode, :commands, 1, [file: '/home/ablu/mana/enet/src/enet_protocol_decode.erl', line: 37]}, {:enet_peer, :handle_event, 3, [file: '/home/ablu/mana/enet/src/enet_peer.erl', line: 813]}, {:gen_statem, :call_state_function, 5, [file: 'gen_statem.erl', line: 1633]}, {:gen_statem, :loop_event_state_function, 6, [file: 'gen_statem.erl', line: 1023]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]
~~~

I will try to do further testing tomorrow :)

The relevant C++ code is:

```c++
    packet = enet_packet_create(msg.getData(),
                                msg.getLength(),
                                ENET_PACKET_FLAG_RELIABLE);

    if (packet)
        enet_peer_send(mRemote, channel, packet);
```

**Comment by flambard** [comment]
The weird thing is that the server is in the state verifying_connect, meaning that the handshake is not yet completed. The server side is waiting for an ACK from the client of the VERIFY_CONNECT command sent by the server.

The client side seems to think the handshake is completed and then your program sends a SEND_RELIABLE command.

The handshake procedure (as I have understood it) copied from enet_peer.erl:

```
%%==============================================================
%% Connection handshake
%%==============================================================
%%
%%
%%      state    client              server     state
%%          (init) *
%%                 |       connect
%%                 |------------------->* (init)
%%    'connecting' |                    | 'acknowledging connect'
%%                 |     ack connect    |
%%                 |<-------------------|
%%  'acknowledging |                    |
%% verify connect' |                    |
%%                 |   verify connect   |
%%                 |<-------------------|
%%                 |                    | 'verifying connect'
%%                 | ack verify connect |
%%                 |------------------->|
%%     'connected' |                    | 'connected'
%%                 |                    |
%%
%%
%%==============================================================
```

**Comment by Ablu** [comment]
Hm... I wonder: why are two messages sent by the server then?
![screenshot from 2018-09-11 17-33-23](https://user-images.githubusercontent.com/741061/45370611-dc6d7080-b5e8-11e8-97ee-b3da9317504e.png)

After receiving the two messages the client sends a packet:
```
80:00:17:67:01:ff:00:01:00:01:17:03:86:00:00:01:00:1f:05:00:00:00:00:09:6c:6f:63:61:6c:68:6f:73:74:25:84:00:08:63:68:61:6e:67:65:4d:65:00:00:00:00
```
![screenshot from 2018-09-11 17-35-30](https://user-images.githubusercontent.com/741061/45370750-26eeed00-b5e9-11e8-84b6-362d5f0a157a.png)

This packet already seems to contain data, but I think enet can group the acks together with the data?

The messages after that seem to be retransmissions due to the missing ack from the server.

**Comment by flambard** [comment]
Yes, the server sends two commands:
1. ACK - for the initial client CONNECT
2. VERIFY_CONNECT - which the client should ACK to complete the handshake

The current implementation does not bundle multiple commands into packets, that is why these commands are sent as two separate packets.

Thanks for the packet data, I will try and see what is going on.

**Comment by Ablu** [comment]
I just debugged the enet code and it definitely sends an ACK upon the verify_connect. It should be embedded into the message which I posted above.

Now, my novice erlange knowledge does not tell me how the code around https://github.com/flambard/enet/blob/a0648210f4a60d2be8b35001229032393aff1e1b/src/enet_peer.erl#L805-L844 is supposed to change the current state before the command is decoded? The ACK seems to be handled further down, so that at least explains why the state is "wrong?". But does this explain why the command decoding fails? Shouldn't that be the same for each state?

**Comment by Ablu** [comment]
Ok, I found a quick way to test my hypothesis: simply force enet to send the ACK alone by triggering a second `enet_host_service` call... and: voilà:
```
21:48:20.769 [error] GenServer #PID<0.180.0> terminating
** (UndefinedFunctionError) function :gproc.ensure_reg_other/3 is undefined or private. Did you mean one of:

      * unreg_other/2

    (gproc) :gproc.ensure_reg_other({:n, :l, {0, {192, 168, 0, 192}, 42470}}, #PID<0.185.0>, #Reference<0.2186439978.734527491.243534>)
    (enet) /home/ablu/mana/enet/src/enet_host.erl:223: :enet_host.handle_cast/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:set_disconnect_trigger, #PID<0.185.0>, 0, {192, 168, 0, 192}, 42470}}
State: {:state, #PID<0.177.0>, #Port<0.4678>, #PID<0.179.0>, #Reference<0.2186439978.734658563.243487>, :undefined, :undefined}
```

So 1st: the error seems to be that the lib does not handle an ACK + a message in the same packet.
And 2nd: there seems to be another error :)

**Comment by Ablu** [comment]
`ensure_reg_other` seems to be a feature of 0.7.0+ (https://github.com/uwiger/gproc/commit/7c0d81abeda7b049e70f7dcc7c9b8bde72a910fc). You seem to reference 0.6.1. So I bumped it (https://github.com/flambard/enet/pull/4), and I get no crashes of processes anymore :).

However, I also do not receive the sent message in my "parent" process :see_no_evil:. But I will try to debug that...

**Comment by flambard** [comment]
Great work!

It looks like there are four "extra" bytes after the second command header. I'm guessing the message your program is sending is the string "localhost", correct?

I have to dig in the original enet code to try understand what they are. Perhaps a checksum?

So, the ACK is actually received, but since it's in the same packet as the following SEND_RELIABLE (which fails to decode) enet_peer never gets to send it to itself and handle it.

**Comment by flambard** [comment]
`80:00:17:67`
Protocol header (16 bits + 16 bits SentTime)

SentTimeIncluded = 1
Compressed = 0
SessionID = 0
PeerID = 0
SentTime = <<23, 103>>


`01:ff:00:01`
Command header (32 bits)

Ack = 0
IsUnsequenced = 0
CommandType = 1 (ACK)
ChannelID = 255 (no channel)
ReliableSequenceNumber = 1

(This is the header for the ACK for VERIFY_CONNECT)


`00:01:17:03`
Acknowledge command (32 bits)

(This is the ACK for VERIFY_CONNECT)



`86:00:00:01`
Command header (32 bits)

Ack = 1
IsUnsequenced = 0
CommandType = 6 (SEND_RELIABLE)
ChannelID = 0
ReliableSequenceNumber = 1

(This is the header for the following SEND_RELIABLE command)


`00:1f:05:00`
**Unknown! (32 bits)**



`00:00:00:09:6c:6f:63:61:6c:68:6f:73:74:25:84:00:08:63:68:61:6e:67:65:4d:65:00:00:00:00`

This looks like a SEND_RELIABLE command with a data length of 9 bytes with a string "localhost" following, and then some more stuff.

**Comment by Ablu** [comment]
Ah, sorry I did not post the message contents:
```c++
    MessageOut msg(GAMSG_REGISTER); // 0x0500
    msg.writeString(gameServerName); // ""
    msg.writeString(gameServerAddress); // "localhost"
    msg.writeInt16(gameServerPort); // 9604
    msg.writeString(password); // "changeMe"
    msg.writeInt32(itemManager->getDatabaseVersion()); // 0
    send(msg);
```
where `writeString()` writes a 16bit length + the string bytes. The `writeIntXXX()` work as you would expect :)

So the (inner) payload should be:
```
  05 00       00 00    00 09  6c 6f 63 61 6c 68 6f 73 74   25 84   00 08  63 68 61 6e 67 65 4d 65   00 00 00 00
| msg type  | length | length l  o  c  a  l  h  o  s  t  | 9604  | length c  h  a  n  g  e  M  e  | 0           |
```

**Comment by Ablu** [comment]
The `05:00` should not be in the header, but part of the message.

**Comment by flambard** [comment]
That explains it! I had mistakenly used 32 bits instead of 16 bits for data length on SEND_RELIABLE.

Will push a fix.

**Comment by flambard** [comment]
OK, fixed in master.

Excellent work Ablu :-)

**Comment by Ablu** [comment]
Thanks a lot for the super-fast fix!

I now correctly receive connects and disconnects in my parent genserver, but the actual message is missing... I will try to debug a bit and see what goes on there...

**Comment by Ablu** [comment]
Hm... I think I hit a mental roadblock (sorry this is my first time tinkering with Erlang code)...

I have this Elixir code:
~~~ex
defmodule ManaElixir.Networking.Enet.Client.LoginServer do
  use GenServer

  def start_link(state) do
    GenServer.start_link(__MODULE__, state)
  end

  def init(state) do
    :enet.start_host(9602, [])
    IO.inspect(self, label: "Me")

    {:ok, state}
  end

  def handle_info(msg, state) do
    IO.inspect(msg, label: "New message")

    {:noreply, state}
  end
end
~~~

And added debug prints to enet as follows: https://github.com/Ablu/enet-1/commit/9258b64a21d7f900ea47c983321d604688a8c2c9.

Now I get this output:
~~~
Me: #PID<0.177.0>
["loop",<0.186.0>]
["got message:",{reliable,<<5,0,0,0,0,9,108,111,99,97,108,104,111,115,116,37,132,0,8,99,104,97,110,103,101,77,101,0,0,0,0>>}]
["reliable:",{<0.186.0>,{recv_reliable,{{command_header,1,0,6,0,1},{reliable,<<5,0,0,0,0,9,108,111,99,97,108,104,111,115,116,37,132,0,8,99,104,97,110,103,101,77,101,0,0,0,0>>}}}}]
New message: {:enet, :connect, :remote, {#PID<0.185.0>, %{0 => #PID<0.186.0>}}, 3982230627}
~~~

Apparently the channels API is called with the message and it sends it to `<0.186.0>`. But the loop in `<0.186.0>` which runs `receive` never actually seems to receive anything at all (and thus also does not forward anything to `Owner`)? (otherwise I would see at least another "loop" print in the output).
How does it never receive the message which is clearly sent to the right process?

Am I misunderstanding anything here?

**Comment by flambard** [comment]
Hypothesis: The reason the channel does not receive the message is that it is waiting for a command with sequence number 0. Apparently, the C implementation uses 1 as the first sequence number (as we can see when decoding the packet by hand).

Pushed a fix with new initial sequence numbers for reliable and unreliable (but sequenced) data.

**Comment by Ablu** [comment]
Heh, I did not read my mails and just came to the same conclusion. I somehow thought a failing guard would also fail the receive, but that does not make any sense of course...

But: Everything (my small little example) works now :). Thanks a lot for the super fast responses!

If you have no objections I would close this issue (it grew fairly large already) and open more specific issues if I find additional incompatibilities?

**Comment by flambard** [comment]
Please do! :-)
